version: '3'

services:
  app:
    image: breeze5690/kleos:v1.2
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"  # Laravel serve
      # - "5173:5173"  # Vite dev server (optional)
    volumes:
      - ./:/var/www
      - ./storage/app/database.sqlite:/var/www/storage/app/database.sqlite
    networks:
      - laravel
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000 & npm run dev -- --host & wait"

networks:
  laravel:
    driver: bridge
